version: "3"

services:
  api:
    build: .
    # must do: 배포 전에 꼭 migration 만들어놔야함.
    command: sh -c "python3 manage.py migrate --noinput && python manage.py collectstatic --noinput && gunicorn -c config/gunicorn.setting.py"
    volumes:
      - .:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/ # 볼륨까지 삭제하려면 docker-down -v
    ports:
      - 5432:5432
    env_file:
      - ./.env.prod.db

volumes:
  postgres_data:
